apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.main.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "netapp-connector.name" . }}
data:
  PORT: {{ .Values.main.env.PORT | quote }}
  PYTHONUNBUFFERED: {{ .Values.main.env.PYTHONUNBUFFERED | quote }}
  DB_PATH: {{ .Values.main.env.DB_PATH | quote }}
