---
plugin:
  name: "netapp-openshift-console-trident"
  namespace: "netapp-openshift-console-trident"
  description: "NetApp Console Plug-in for Red Hat OpenShift provides a single pane integration with NetApp Intelligent Data Management solutions for containers and virtual machines"
  image:
    repository: ghcr.io/netapp/netapp-openshift-console-trident
    tag: 25.7.16
    pullPolicy: Always 
  imageCredentials:
    registry: ghcr.io
    username: ""
    token: ""
  replicas: 2
  port: 9443
  securityContext:
    enabled: true
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
  basePath: /
  serviceAccount:
    create: false
    annotations: {}
    name: "netapp-openshift-console-trident-serviceaccount"
  patcherServiceAccount:
    create: false
    annotations: {}
    name: "netapp-openshift-console-trident-patcher"
  jobs:
    patchConsoles:
      enabled: false
      image: "registry.redhat.io/openshift4/ose-tools-rhel8@sha256:e44074f21e0cca6464e50cb6ff934747e0bd11162ea01d522433a1a1ae116103"
      podSecurityContext:
        enabled: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        enabled: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
