apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netapp-neo.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  WORKER_SERVICE_URL: {{ include "netapp-neo.workerUrl" . | quote }}
  NER_SERVICE_URL: {{ include "netapp-neo.nerUrl" . | quote }}
