apiVersion: v1
kind: Service
metadata:
  name: {{ include "netapp-neo.fullname" . }}-extractor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
    app.kubernetes.io/component: extractor
spec:
  type: {{ .Values.extractor.service.type }}
  ports:
    - port: {{ .Values.extractor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "netapp-neo.selectorLabels" (dict "context" . "component" "extractor") | nindent 4 }}
