{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-neo.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "netapp-neo.databaseUrl" . | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
{{- end }}
