{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netapp-neo.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "netapp-neo.selectorLabels" (dict "context" . "component" "postgres") | nindent 4 }}
{{- end }}
