apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-neo.fullname" . }}-encryption
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
type: Opaque
stringData:
  ENCRYPTION_KEY: {{ .Values.api.env.ENCRYPTION_KEY | quote }}
