apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-neo.fullname" . }}-jwt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.api.env.JWT_SECRET_KEY | quote }}
