apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-neo.fullname" . }}-openai
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.extractor.env.OPENAI_API_KEY | quote }}
