apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-neo.fullname" . }}-graph
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
type: Opaque
stringData:
  MS_GRAPH_TENANT_ID: {{ .Values.api.env.MS_GRAPH_TENANT_ID | quote }}
  MS_GRAPH_CLIENT_ID: {{ .Values.api.env.MS_GRAPH_CLIENT_ID | quote }}
  MS_GRAPH_CLIENT_SECRET: {{ .Values.api.env.MS_GRAPH_CLIENT_SECRET | quote }}
  MS_GRAPH_CONNECTOR_ID: {{ .Values.api.env.MS_GRAPH_CONNECTOR_ID | quote }}
