apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-neo.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
type: Opaque
stringData:
  NETAPP_CONNECTOR_LICENSE: {{ .Values.api.env.NETAPP_CONNECTOR_LICENSE | quote }}
  CONNECTOR_ID: {{ .Values.api.env.CONNECTOR_ID | quote }}
