{{- if .Values.openshift.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netapp-neo.apiServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.openshift.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}

{{- if .Values.openshift.ui.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netapp-neo.uiServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- with .Values.openshift.ui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}

{{- if and .Values.openshift.privilegedWorkloads.worker.enabled .Values.openshift.privilegedWorkloads.worker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netapp-neo.workerPrivilegedServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with .Values.openshift.privilegedWorkloads.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}

{{- if and .Values.openshift.privilegedWorkloads.extractor.enabled .Values.openshift.privilegedWorkloads.extractor.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netapp-neo.extractorPrivilegedServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
    app.kubernetes.io/component: extractor
  {{- with .Values.openshift.privilegedWorkloads.extractor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}