apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netapp-neo.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-neo.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
data:
  EXTRACTOR_SERVICE_URL: {{ include "netapp-neo.extractorUrl" . | quote }}
  {{- if .Values.ner.enabled }}
  NER_SERVICE_URL: {{ include "netapp-neo.nerUrl" . | quote }}
  {{- end }}
  {{- range $key, $val := .Values.worker.environments }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
