apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  annotations:
    capability.openshift.io/name: Console
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  generation: 1
  name: netapp-trident-protect
  labels:
    vendor: netapp
spec:
  conclusion: You can now backup and mirror your containerized and virtualized application with NetApp Trident Protect.
  description: Install Trident Protect to manage your application's backups and mirrors.
  displayName: Deploy NetApp Trident Protect. 
  durationMinutes: 20
  icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAwIDkwOS4wOTEiIHhtbDpzcGFjZT0icHJlc2VydmUiIHdpZHRoPSIyNDAwIiBoZWlnaHQ9IjE4MTAiPgogIDxwYXRoIGQ9Ik03ODcuODc5IDQzNC41NDVoMTYuODE4djguNDg1YzQuMDkxLTUuNDU1IDkuNjk3LTkuNTQ1IDE4LjQ4NS05LjU0NSAxMy43ODggMCAyNi45NyAxMC43NTggMjYuOTcgMzAuNjA2di4xNTJjMCAxOS44NDgtMTIuODc5IDMwLjYwNi0yNi45NyAzMC42MDYtOC45MzkgMC0xNC41NDUtNC4wOTEtMTguNDg1LTguNzg4djI1LjQ1NWgtMTYuODE4em00NS40NTUgMjkuNjk3di0uMTUyYzAtOS44NDgtNi42NjctMTYuMzY0LTE0LjU0NS0xNi4zNjRzLTE0LjM5NCA2LjUxNS0xNC4zOTQgMTYuMzY0di4xNTJjMCA5Ljg0OCA2LjUxNSAxNi4zNjQgMTQuMzk0IDE2LjM2NHMxNC41NDUtNi4zNjQgMTQuNTQ1LTE2LjM2NG0tMzc4LjkzOS00OC4zMzNoMTUuNzU4bDM2LjIxMiA0OC4xODJ2LTQ4LjE4MmgxNi44MTh2NzcuODc5aC0xNC41NDVsLTM3LjQyNi00OS4yNDN2NDkuMjQyaC0xNi44MTh6bTc2Ljk3IDQ4LjYzNnYtLjE1MmMwLTE2Ljk3IDEyLjEyMS0zMC43NTggMjkuMjQyLTMwLjc1OCAxOS44NDggMCAyOC43ODggMTUuMzAzIDI4Ljc4OCAzMi4xMjEgMCAxLjM2NC0uMTUyIDIuODc5LS4xNTIgNC4zOTRoLTQxLjIxMmMxLjY2NyA3LjU3NiA2Ljk3IDExLjY2NyAxNC41NDUgMTEuNjY3IDUuNjA2IDAgOS42OTctMS44MTggMTQuMzk0LTYuMDYxbDkuNTQ1IDguNDg1Yy01LjQ1NSA2LjgxOC0xMy40ODUgMTEuMDYxLTI0LjI0MiAxMS4wNjEtMTcuODc5LS4xNTItMzAuOTA5LTEyLjcyNy0zMC45MDktMzAuNzU4bTQxLjY2Ny01Yy0xLjA2MS03LjU3Ni01LjQ1NS0xMi41NzYtMTIuNDI0LTEyLjU3NnMtMTEuNTE1IDUtMTIuODc5IDEyLjU3NnptMjYuOTcgMTcuNDI0di0yOC4wM2gtNy4xMjF2LTE0LjM5NEg2MDB2LTE1LjE1MmgxNi42Njd2MTUuMTUyaDEzLjkzOXYxNC4zOTRoLTEzLjkzOXYyNS4zMDNjMCAzLjkzOSAxLjY2NyA1Ljc1OCA1LjQ1NSA1Ljc1OCAzLjAzIDAgNS45MDktLjc1OCA4LjMzMy0yLjEyMXYxMy40ODVjLTMuNDg1IDIuMTIxLTcuNTc2IDMuNDg1LTEzLjMzMyAzLjQ4NS0xMC4xNTItLjE1Mi0xNy4xMjEtNC4yNDItMTcuMTIxLTE3Ljg3OW0xMTguOTM5LTQyLjQyNGgxNi44MTh2OC40ODVjNC4wOTEtNS40NTUgOS42OTctOS41NDUgMTguNDg1LTkuNTQ1IDEzLjc4OCAwIDI2Ljk3IDEwLjc1OCAyNi45NyAzMC42MDZ2LjE1MmMwIDE5Ljg0OC0xMi44NzkgMzAuNjA2LTI2Ljk3IDMwLjYwNi04LjkzOSAwLTE0LjU0NS00LjA5MS0xOC40ODUtOC43ODh2MjUuNDU1SDcxOC45NHptNDUuMzAzIDI5LjY5N3YtLjE1MmMwLTkuODQ4LTYuNjY3LTE2LjM2NC0xNC41NDUtMTYuMzY0cy0xNC4zOTQgNi41MTUtMTQuMzk0IDE2LjM2NHYuMTUyYzAgOS44NDggNi41MTUgMTYuMzY0IDE0LjM5NCAxNi4zNjQgOC4wMyAwIDE0LjU0NS02LjM2NCAxNC41NDUtMTYuMzY0bS05Ny4xMjEtNDguNDg1aDE1LjMwM2wzMi4yNzMgNzcuODc5SDY5Ni45N2wtNy4xMjEtMTcuNDI0aC0zMC43NThsLTcuMTIxIDE3LjQyNGgtMTcuMjczem0xNy43MjcgNDUuNjA2LTEwLjMwMy0yNS4xNTItMTAuMzAzIDI1LjE1MnptLTM1Ny41NzYtNDUuNDU1djc3Ljg3OWgzNi4zNjRWNDQ2Ljk3aDIwLjc1OHY0Ni44MThoMzYuMzY0di03Ny44Nzl6Ii8+Cjwvc3ZnPgo=
  introduction: |- 
    ### Deploy NetApp Trident Protect
    For additional information, see the [NetApp Trident Protect documentation](https://docs.netapp.com/us-en/trident/trident-protect/learn-about-trident-protect.html).
  nextQuickStart:
  - netapp-trident-protect-backup
  tasks:
  - description: |-
      To add the Trident Protect Helm repository:

      1. Click on the [perspective switcher]{{`{{highlight qs-perspective-switcher}}`}} at the top of the navigation, and select **Developer**.

      2. In the navigation menu, click [Import]{{`{{highlight qs-masthead-import}}`}} and copy/paste the following to create a namespace:
      ```YAML
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        name: trident-protect
        labels:
          'susanoo.trident.netapp.io': 'true'
      ```

      3. Scroll down and click **Create**.

      4. Click [Helm]{{`{{highlight qs-nav-helm}}`}}, then **Create**, and select **Repository** from the dropdown menu to 
        - fill the form to add the Helm Repository with this URL: **https://netapp.github.io/trident-protect-helm-chart** or
        - use the following YAML definition:
      ```
      ---
      apiVersion: helm.openshift.io/v1beta1
      kind: ProjectHelmChartRepository
      metadata:
        name: trident-protect
        namespace: trident-protect
      spec:
        connectionConfig:
          url: 'https://netapp.github.io/trident-protect-helm-chart'
        name: trident-protect
      ```

      5. Scroll down and click **Create**.

    review:
      failedTaskHelp: This task isn’t verified yet. Try the task again.
      instructions: |-
        #### To verify the application was successfully created:
        1. Do you see the NetApp Trident Protect Helm repository in the **Helm** view within the **trident-protect** namespace?
    summary:
      failed: Try the steps again.
      success: You added the Netpp Trident Protect Helm repository!
    title: Add the Trident Protect Helm repository
  - description: |-
      To add the Trident Protect Custom Resource Definitions (CRDs):

      1. Click [Helm]{{`{{highlight qs-nav-helm}}`}}, then **Create**, and select **Helm Release** from the dropdown menu. 
      2. From the Helm Charts catalog, filter down the items by typing **trident**, and click the tile **Trident Protect Crds** chart.
      3. Click on **Create**, select the latest version in the **Chart version** dropdown menu, and then click **Create**.
      
      Once created, the [Helm]{{`{{highlight qs-nav-helm}}`}} view will show the **trident-protect-crds** deployment in **Helm Releases** within the **trident-protect** namespace.

    review:
      failedTaskHelp: This task isn’t verified yet. Try the task again.
      instructions: |-
        #### To verify the build is complete:
        Do you see the **trident-protect-crds** deployment in the **Helm Releases** view within the **trident-protect** namespace?
    summary:
      failed: Try the steps again.
      success: All the NetApp Trident Protect CRS are now deployed!
    title: Deploy the Trident Protect CRDs
  - description: |-
      To deploy the Trident Protect Controller:

      1. Click [Helm]{{`{{highlight qs-nav-helm}}`}}, then **Create**, and select **Helm Release** from the dropdown menu. 
      2. From the Helm Charts catalog, filter down the items by typing **trident**, and click the tile **Trident Protect** chart.
      3. Click on **Create**, select the latest version in the **Chart version** dropdown menu, and then click **Create**.

      Note: in this view, a code editor will open allowing you to customize the deployment. One of the most common customizations is to change the opt-in **telemtry** from:
      ```YAML
      autoSupport:
        enabled: true
      ```
      to the following to opt-out:
      ```YAML
      autoSupport:
        enabled: false
      ```

      Once created, the [Helm]{{`{{highlight qs-nav-helm}}`}} view will show the **trident-protect** deployment in **Helm Releases** within the **trident-protect** namespace. 

      Also, in [Topology]{{`{{highlight qs-nav-topology}}`}}, a Trident Protect **Deployment** should appear.

    review:
      failedTaskHelp: This task isn’t verified yet. Try the task again.
      instructions: |-
        Do you see the **trident-protect** deployment in the **Helm Releases** view within the **trident-protect** namespace? 

        Do you see the Trident Protect **Deployment** in the **Topology** view?
    summary:
      failed: Try the steps again.
      success: Contragulations, you deployed the Trident Protect Controller and can now manage your application's backups and mirrors!
    title: Deploy the Trident Protect Controller

