apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: {{ .Values.plugin.name }}
  namespace: {{ .Values.plugin.namespace }}
  labels:
    {{- include "netapp-openshift-console-protect.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.plugin.port }}-tcp
      protocol: TCP
      port: {{ .Values.plugin.port }}
      targetPort: {{ .Values.plugin.port }}
  selector:
    {{- include "netapp-openshift-console-protect.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  sessionAffinity: None
