{{- if .Values.plugin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netapp-openshift-console-protect.serviceAccount.name" . }}
  labels:
    {{- include "netapp-openshift-console-protect.labels" . | nindent 4 }}
  {{- with .Values.plugin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
