apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.main.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "netapp-connector.name" . }}
stringData:
  MS_GRAPH_CONNECTOR_ID: {{ .Values.main.credentials.MS_GRAPH_CONNECTOR_ID | quote }}
  MS_GRAPH_CLIENT_ID: {{ .Values.main.credentials.MS_GRAPH_CLIENT_ID | quote }}
  MS_GRAPH_CLIENT_SECRET: {{ .Values.main.credentials.MS_GRAPH_CLIENT_SECRET | quote }}
  MS_GRAPH_TENANT_ID: {{ .Values.main.credentials.MS_GRAPH_TENANT_ID | quote }}
  NETAPP_CONNECTOR_LICENSE: {{ .Values.main.credentials.NETAPP_CONNECTOR_LICENSE | quote }}