{{- if .Values.main.env.SSL_CERT_FILE }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.main.name }}-ssl-cert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  custom_ca_bundle.pem: {{ .Values.main.env.SSL_CERT_FILE | b64enc }}
{{- end }}