apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.plugin.name }}-deployment
  namespace: {{ .Values.plugin.namespace }}
  labels:
    {{- include "netapp-openshift-console-trident.labels" . | nindent 4 }}
    app.openshift.io/runtime-namespace: {{ .Values.plugin.namespace }}
spec:
  replicas: {{ .Values.plugin.replicas }}
  selector:
    matchLabels:
      {{- include "netapp-openshift-console-trident.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
            {{- include "netapp-openshift-console-trident.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.plugin.name }}-registry-secret
      containers:
        - name: {{ template "netapp-openshift-console-trident.name" . }}
          image: "{{ .Values.plugin.image.repository }}:{{ default .Chart.AppVersion .Values.plugin.image.tag }}"
          ports:
            - containerPort: {{ .Values.plugin.port }}
              protocol: TCP
          imagePullPolicy: {{ .Values.plugin.image.pullPolicy }}
          {{- if and (.Values.plugin.securityContext.enabled) (.Values.plugin.containerSecurityContext) }}
          securityContext: {{ tpl (toYaml (omit .Values.plugin.containerSecurityContext "enabled")) $ | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.plugin.resources | nindent 12 }}
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
            - name: netapp-openshift-console-trident-nginx-config
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
        - name: netapp-openshift-console-trident-nginx-config
          configMap:
            name: {{ .Values.plugin.name }}
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
