apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.plugin.name }}-registry-secret
  namespace: {{ .Values.plugin.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}